### ISSUE TITLE
Add "Traditional Chinese" in addition to "Simplified Chinese"

### ISSUE THREAD

**Issue by tijptjik** [ODHK/opengov.hk#13] opened 2014-03-18 07:48 UTC
I also note that currently only "Simplified Chinese" is available;
let's change that before showing the site to anyone else, as you know
how sensitive some people can be about this ;)

Send PR to the Froide code-base

**Comment by gfrmin** [comment] 2014-04-25 07:59
What's progress on this? Looking at https://github.com/okfde/fragdenstaat_de/blob/master/fragdenstaat_de/settings.py indicates we should be able to set languages by ourselves?

**Comment by milkcask** [comment] 2014-05-10 09:17
Duplicate of issue #1 
- done upstream https://github.com/stefanw/froide/pull/119

**Comment by gfrmin** [comment] 2014-05-11 13:40
This change has not been pulled into this theme and so this ticket has not been completed yet.

**Comment by gfrmin** [comment] 2014-05-11 13:41
It is also not a duplicate of #1. This ticket is about adding Traditional Chinese as a language option in the menu at the top right of the screen, while #1 is about completing the translation of the site into Traditional Chinese.

**Closed as completed** 2014-05-11 16:01 UTC
